#!/bin/bash

./build || exit

echo Copying...
rsync -az ./api root@whooplist.com:/srv/www/api.whooplist.com/
if [ $? -ne 0 ]; then
    echo Copy failed, exiting
    rm ./api
    exit
fi
rm ./api
echo Restarting...
ssh root@whooplist.com "systemctl restart whooplist-api.service"
echo Done!
